### ISSUE TITLE
NameError (uninitialized constant Settings):

### ISSUE THREAD

**Issue by marcalc** [fredwu/angel_nest#21]
Any request gives me this error.

I'm using MRI 1.9.3 and Rails 3.1.rc6.

Is it something with rails_config gem?

**Comment by fredwu** [comment]
Might have something to do with the new file loading changes in 1.9.3, I'll have to find some time to test it against 1.9.3.

I see that you've created a ticket in rails_config, so I'll close this one here and keep the conversation over there. :)
