### ISSUE TITLE
keep sidebar 30% of page consistant across the site.

### ISSUE THREAD

**Issue by gitfly** [fredwu/angel_nest#4]
login in as fredwu, sidebar is 30% of the page, click on any user, the side page became 50% of the page. needs to be consistant. I think about 30% is fine for us.

**Comment by fredwu** [comment]
This is intentional - to keep it consistent with startup profiles. The left hand side area will be tweaked to resemble the startup profile layout.

**Comment by gitfly** [comment]
OK , this is a similar page to the home page, please make it consistant as the home page. I don't know what you plan to put the left hand side.  We need to refer back the original wireframes.

**Comment by fredwu** [comment]
This **is** designed according to the wireframes.
