### ISSUE TITLE
Navigation issue: no easy way to go back the home page

### ISSUE THREAD

**Issue by gitfly** [fredwu/angel_nest#5]
sign out and sign back in can get me to the home page. add home icon or link at the top.

**Comment by gitfly** [comment]
this issue was misunderstood. I meant there is no easy or obvious way to go to current user's home page. An easy way to fix this would be to change the link to the current user name "Fred Wu" to the home page instead of user page. changed this to medium priority however.

**Comment by fredwu** [comment]
There is a 'home' button added to the navigation menu. And clicking on the logo takes you to the home page as well.
